<h1>V2 of Buy top 10 of Nasdaq 100</h1>

215 tickers that have been in the Nasdaq 100 index since 2010...

In [93]:
from vectorbtpro import *
from datetime import timedelta
import numpy as np
import pandas as pd
import yfinance as yf
import pytz
import datetime


# Load the CSV file
file_path = 'data/nasdaq_100_index.csv'
df = pd.read_csv(file_path)

# Rename columns for easier reference
df.columns = ['Date'] + [f'Ticker{i}' for i in range(1, len(df.columns))]

# Get all tickers by dropping the 'Date' column and flattening
all_tickers = df.drop('Date', axis=1).values.flatten()

# Remove NaN values and find unique tickers using pandas Series
unique_tickers = pd.Series(all_tickers).dropna().unique()

# Sort the unique tickers alphabetically
sorted_unique_tickers = sorted(unique_tickers)

# Get the number of unique tickers
num_sorted_unique_tickers = len(sorted_unique_tickers)

# Display the sorted unique tickers and their count
print(f"Sorted unique tickers: {sorted_unique_tickers}")
print(f"Number of unique tickers: {num_sorted_unique_tickers}")

Sorted unique tickers: ['AAL', 'AAPL', 'ABNB', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AEP', 'AKAM', 'ALGN', 'ALTR', 'ALXN', 'AMAT', 'AMD', 'AMGN', 'AMZN', 'ANSS', 'APOL', 'ARM', 'ASML', 'ATVI', 'ATYR', 'AVGO', 'AZN', 'BBBY', 'BIDU', 'BIIB', 'BKNG', 'BKR', 'BMC', 'BMRN', 'CCEP', 'CDNS', 'CDW', 'CEG', 'CELG', 'CEPH', 'CERN', 'CHKP', 'CHRW', 'CHTR', 'CMCSA', 'COST', 'CPRT', 'CRWD', 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTRX', 'CTSH', 'CTXS', 'DASH', 'DDOG', 'DELL', 'DISH', 'DLTR', 'DOCU', 'DTV', 'DXCM', 'EA', 'EBAY', 'ENDP', 'ENPH', 'EQIX', 'ESRX', 'EXC', 'EXPD', 'EXPE', 'FANG', 'FAST', 'FFIV', 'FI', 'FLEX', 'FLIR', 'FOSL', 'FOX', 'FOXA', 'FSLR', 'FTNT', 'FWLT', 'GEHC', 'GEN', 'GENZ', 'GFS', 'GILD', 'GOLD', 'GOOG', 'GOOGL', 'GRMN', 'HAS', 'HOLX', 'HON', 'HSIC', 'IAC', 'IDXX', 'ILMN', 'INCY', 'INFY', 'INTC', 'INTU', 'ISRG', 'JBHT', 'JD', 'JOY', 'KDP', 'KHC', 'KLAC', 'LBTYA', 'LCID', 'LIN', 'LLTC', 'LOGI', 'LRCX', 'LULU', 'MAR', 'MAT', 'MCHP', 'MDB', 'MDLZ', 'MELI', 'META', 'MNST', 'MRNA', 'MRVL', 'MSFT', 'MTCH', 'MU', 'MXIM', 'NCLH', 'NFLX', 'NIHD', 'NTAP', 'NTES', 'NUAN', 'NVDA', 'NXPI', 'ODFL', 'OKTA', 'ON', 'ORCL', 'ORLY', 'PANW', 'PARA', 'PAYX', 'PCAR', 'PDCO', 'PDD', 'PEP', 'PPD', 'PRGO', 'PTON', 'PYPL', 'QCOM', 'QGEN', 'QRTEA', 'REGN', 'RIVN', 'ROP', 'ROST', 'RYAAY', 'SBAC', 'SBUX', 'SGEN', 'SHLDQ', 'SHPG', 'SIAL', 'SIRI', 'SMCI', 'SNDK', 'SNPS', 'SPLK', 'SPLS', 'SRCL', 'STLD', 'STRZA', 'STX', 'SWKS', 'TCOM', 'TEAM', 'TEVA', 'TFCF', 'TFCFA', 'TIGO', 'TMUS', 'TRIP', 'TSCO', 'TSLA', 'TTD', 'TTWO', 'TXN', 'UAL', 'ULTA', 'URBN', 'VEON', 'VMED', 'VOD', 'VRSK', 'VRSN', 'VRTX', 'VTRS', 'WBA', 'WBD', 'WCRX', 'WDAY', 'WDC', 'WFM', 'WTW', 'WYNN', 'XEL', 'XLNX', 'XRAY', 'YHOO', 'ZM', 'ZS']
Number of unique tickers: 215

In [94]:
# Define start and end date for historical data
FROMDATE = datetime.datetime(2009, 1, 1, tzinfo=pytz.utc)
TODATE = datetime.datetime(2024, 10, 10, tzinfo=pytz.utc)

start_date = FROMDATE
end_date = TODATE

# Download historical data for valid tickers using vectorbtpro
#data = vbt.YFData.pull(sorted_unique_tickers, start=start_date, end=end_date, missing_columns="drop")
#data = data.loc[(data.wrapper.index >= start_date) & (data.wrapper.index < end_date)]

In [5]:
# Import the historical Close price data
data = vbt.Data.from_csv("data/yahoo/daily")

# Create a list of available tickers in the data
available_tickers_in_data = data.columns.tolist()

print(f"available_tickers_in_data: {available_tickers_in_data}")

 22%|##2       | 40/181 [00:02<00:07, 19.57it/s, symbol=CSX]

available_tickers_in_data: ['AAL', 'AAPL', 'ABNB', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AEP', 'AKAM', 'ALGN', 'ALTR', 'AMAT', 'AMD', 'AMGN', 'AMZN', 'ANSS', 'ARM', 'ASML', 'ATYR', 'AVGO', 'AZN', 'BIDU', 'BIIB', 'BKNG', 'BKR', 'BMC', 'BMRN', 'CCEP', 'CDNS', 'CDW', 'CEG', 'CHKP', 'CHRW', 'CHTR', 'CMCSA', 'COST', 'CPRT', 'CRWD', 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTSH', 'DASH', 'DDOG', 'DELL', 'DLTR', 'DOCU', 'DXCM', 'EA', 'EBAY', 'ENPH', 'EQIX', 'ESRX', 'EXC', 'EXPD', 'EXPE', 'FANG', 'FAST', 'FFIV', 'FI', 'FLEX', 'FOSL', 'FOX', 'FOXA', 'FSLR', 'FTNT', 'GEHC', 'GEN', 'GFS', 'GILD', 'GOLD', 'GOOG', 'GOOGL', 'GRMN', 'HAS', 'HOLX', 'HON', 'HSIC', 'IAC', 'IDXX', 'ILMN', 'INCY', 'INFY', 'INTC', 'INTU', 'ISRG', 'JBHT', 'JD', 'KDP', 'KHC', 'KLAC', 'LBTYA', 'LCID', 'LIN', 'LOGI', 'LRCX', 'LULU', 'MAR', 'MAT', 'MCHP', 'MDB', 'MDLZ', 'MELI', 'META', 'MNST', 'MRNA', 'MRVL', 'MSFT', 'MTCH', 'MU', 'NCLH', 'NFLX', 'NTAP', 'NTES', 'NVDA', 'NXPI', 'ODFL', 'OKTA', 'ON', 'ORCL', 'ORLY', 'PANW', 'PARA', 'PAYX', 'PCAR', 'PDCO', 'PDD', 'PEP', 'PRGO', 'PTON', 'PYPL', 'QCOM', 'QGEN', 'QRTEA', 'REGN', 'RIVN', 'ROP', 'ROST', 'RYAAY', 'SBAC', 'SBUX', 'SHPG', 'SIRI', 'SMCI', 'SNPS', 'SRCL', 'STLD', 'STX', 'SWKS', 'TCOM', 'TEAM', 'TEVA', 'TIGO', 'TMUS', 'TRIP', 'TSCO', 'TSLA', 'TTD', 'TTWO', 'TXN', 'UAL', 'ULTA', 'URBN', 'VEON', 'VMED', 'VOD', 'VRSK', 'VRSN', 'VRTX', 'VTRS', 'WBA', 'WBD', 'WDAY', 'WDC', 'WTW', 'WYNN', 'XEL', 'XRAY', 'ZM', 'ZS']

In [95]:
ms_points = data.wrapper.get_index_points(every="90D")
ms_points

array([   0,   63,  125,  187,  248,  310,  373,  436,  498,  560,  622,
        684,  747,  808,  871,  933,  993, 1054, 1116, 1178, 1242, 1302,
       1365, 1427, 1489, 1549, 1612, 1676, 1738, 1798, 1862, 1924, 1986,
       2047, 2110, 2173, 2235, 2295, 2358, 2420, 2483, 2543, 2606, 2668,
       2730, 2790, 2853, 2915, 2979, 3039, 3102, 3164, 3227, 3287, 3350,
       3412, 3476, 3535, 3598, 3659, 3722, 3783, 3845, 3907])

In [96]:
data.wrapper.index[ms_points]

DatetimeIndex(['2009-01-02 05:00:00+00:00', '2009-04-03 04:00:00+00:00',
               '2009-07-02 04:00:00+00:00', '2009-09-30 04:00:00+00:00',
               '2009-12-28 05:00:00+00:00', '2010-03-29 04:00:00+00:00',
               '2010-06-28 04:00:00+00:00', '2010-09-27 04:00:00+00:00',
               '2010-12-23 05:00:00+00:00', '2011-03-24 04:00:00+00:00',
               '2011-06-22 04:00:00+00:00', '2011-09-20 04:00:00+00:00',
               '2011-12-19 05:00:00+00:00', '2012-03-19 04:00:00+00:00',
               '2012-06-18 04:00:00+00:00', '2012-09-14 04:00:00+00:00',
               '2012-12-12 05:00:00+00:00', '2013-03-13 04:00:00+00:00',
               '2013-06-11 04:00:00+00:00', '2013-09-09 04:00:00+00:00',
               '2013-12-09 05:00:00+00:00', '2014-03-07 05:00:00+00:00',
               '2014-06-06 04:00:00+00:00', '2014-09-04 04:00:00+00:00',
               '2014-12-02 05:00:00+00:00', '2015-03-02 05:00:00+00:00',
               '2015-06-01 04:00:00+00:00', '2015-08-31 04:00:00+00:00',
               '2015-11-27 05:00:00+00:00', '2016-02-25 05:00:00+00:00',
               '2016-05-26 04:00:00+00:00', '2016-08-24 04:00:00+00:00',
               '2016-11-21 05:00:00+00:00', '2017-02-21 05:00:00+00:00',
               '2017-05-22 04:00:00+00:00', '2017-08-21 04:00:00+00:00',
               '2017-11-16 05:00:00+00:00', '2018-02-14 05:00:00+00:00',
               '2018-05-16 04:00:00+00:00', '2018-08-14 04:00:00+00:00',
               '2018-11-12 05:00:00+00:00', '2019-02-11 05:00:00+00:00',
               '2019-05-13 04:00:00+00:00', '2019-08-09 04:00:00+00:00',
               '2019-11-06 05:00:00+00:00', '2020-02-04 05:00:00+00:00',
               '2020-05-05 04:00:00+00:00', '2020-08-03 04:00:00+00:00',
               '2020-11-02 05:00:00+00:00', '2021-01-29 05:00:00+00:00',
               '2021-04-30 04:00:00+00:00', '2021-07-29 04:00:00+00:00',
               '2021-10-27 04:00:00+00:00', '2022-01-24 05:00:00+00:00',
               '2022-04-25 04:00:00+00:00', '2022-07-25 04:00:00+00:00',
               '2022-10-24 04:00:00+00:00', '2023-01-19 05:00:00+00:00',
               '2023-04-20 04:00:00+00:00', '2023-07-19 04:00:00+00:00',
               '2023-10-17 04:00:00+00:00', '2024-01-16 05:00:00+00:00',
               '2024-04-15 04:00:00+00:00', '2024-07-15 04:00:00+00:00'],
              dtype='datetime64[ns, UTC]', name='Date', freq=None)

In [97]:
data.wrapper.index[ms_points[0]]

Timestamp('2009-01-02 05:00:00+0000', tz='UTC')

In [98]:
data.data["AAPL"]

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2009-01-02 05:00:00+00:00,2.590126,2.745751,2.568412,2.737004,746015200,0.0,0.0
2009-01-05 05:00:00+00:00,2.809991,2.900772,2.796117,2.852516,1181608400,0.0,0.0
2009-01-06 05:00:00+00:00,2.893836,2.930630,2.786467,2.805467,1289310400,0.0,0.0
2009-01-07 05:00:00+00:00,2.768975,2.789784,2.722226,2.744846,753048800,0.0,0.0
2009-01-08 05:00:00+00:00,2.727353,2.809388,2.715590,2.795815,673500800,0.0,0.0
...,...,...,...,...,...,...,...
2024-10-03 04:00:00+00:00,225.139999,226.809998,223.320007,225.669998,34044200,0.0,0.0
2024-10-04 04:00:00+00:00,227.899994,228.000000,224.130005,226.800003,37245100,0.0,0.0
2024-10-07 04:00:00+00:00,224.500000,225.690002,221.330002,221.690002,39505400,0.0,0.0
2024-10-08 04:00:00+00:00,224.300003,225.979996,223.250000,225.770004,31855700,0.0,0.0
2024-10-09 04:00:00+00:00,225.229996,229.750000,224.830002,229.539993,33591100,0.0,0.0

In [99]:
symbol_wrapper = data.get_symbol_wrapper(freq="1d")
filled_allocations = symbol_wrapper.fill()
filled_allocations

symbol,AAL,AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AKAM,ALGN,...,WBA,WBD,WDAY,WDC,WTW,WYNN,XEL,XRAY,ZM,ZS
Date,,,,,,,,,,,,,,,,,,,,,
2009-01-02 05:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-05 05:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-06 05:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-07 05:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-08 05:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03 04:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-04 04:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-07 04:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-08 04:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-09 04:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
data.get("Close")

symbol,AAL,AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AKAM,ALGN,...,WBA,WBD,WDAY,WDC,WTW,WYNN,XEL,XRAY,ZM,ZS
Date,,,,,,,,,,,,,,,,,,,,,
2009-01-02 05:00:00+00:00,7.909603,2.737004,NaN,23.020000,13.429654,24.093952,20.680000,18.165882,15.740000,8.890000,...,15.770761,7.485948,NaN,9.898497,47.575073,28.829100,10.779800,25.546339,NaN,NaN
2009-01-05 05:00:00+00:00,7.853037,2.852516,NaN,23.129999,13.361378,23.849491,20.879999,18.000259,16.180000,9.250000,...,16.567011,7.562596,NaN,9.649632,46.915359,31.795898,10.676808,24.703865,NaN,NaN
2009-01-06 05:00:00+00:00,8.541240,2.805467,NaN,24.219999,14.009989,24.332449,20.850000,17.690359,16.450001,9.600000,...,16.486767,7.659683,NaN,11.496066,48.894512,33.607609,10.539487,24.045675,NaN,NaN
2009-01-07 05:00:00+00:00,8.560093,2.744846,NaN,24.230000,13.484271,23.915083,20.070000,17.498016,15.470000,9.360000,...,16.684298,7.439959,NaN,10.853827,48.819099,28.713581,10.430777,24.115879,NaN,NaN
2009-01-08 05:00:00+00:00,9.022036,2.795815,NaN,24.290001,13.497931,24.213192,19.200001,17.781191,15.510000,9.010000,...,16.567011,7.705672,NaN,10.950163,49.252625,28.239384,10.568096,24.405483,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03 04:00:00+00:00,10.820000,225.669998,125.290001,503.799988,226.559998,284.619995,268.589996,101.370003,100.449997,236.970001,...,8.670000,7.740000,240.940002,66.580002,290.589996,103.080002,64.400002,24.709999,67.209999,169.630005
2024-10-04 04:00:00+00:00,11.510000,226.800003,129.850006,507.220001,228.229996,285.160004,271.160004,100.279999,101.480003,241.350006,...,8.720000,7.780000,242.350006,66.349998,290.690002,105.449997,63.730000,25.219999,68.660004,173.929993
2024-10-07 04:00:00+00:00,11.530000,221.690002,130.229996,487.299988,226.509995,282.119995,267.230011,98.059998,101.169998,234.850006,...,8.870000,7.720000,235.470001,66.440002,287.989990,106.410004,63.009998,24.480000,68.160004,172.130005
2024-10-08 04:00:00+00:00,11.920000,225.770004,132.500000,496.239990,229.399994,285.420013,275.079987,98.199997,101.330002,234.059998,...,9.080000,7.720000,239.470001,66.169998,292.940002,102.879997,62.930000,24.480000,68.320000,176.929993
2024-10-09 04:00:00+00:00,11.930000,229.539993,135.490005,494.079987,233.240005,287.769989,276.880005,97.720001,103.110001,233.789993,...,8.910000,7.730000,240.770004,64.480003,298.049988,104.150002,62.580002,24.520000,69.970001,185.970001

<h2>GENERATING ALLOCATIONS USING ALL TICKERS IN DATA</h2>
THIS IS BASCILY OVERFITTING, AS WE ALLOW BUY TICKERS THAT WAS NOT IN THE NASDAQ 100 AT REBALANCING

In [102]:
# Import necessary libraries
import numpy as np
import pandas as pd

# Get the close prices data
close_prices = data.get("Close")

# Define the allocation function to calculate performance between consecutive points
def top_performers_allocate_func(current_idx, previous_idx):
    # Calculate the percentage change between current and previous idx
    if previous_idx is not None:
        # Percentage change for each ticker
        pct_change = (close_prices.iloc[current_idx] / close_prices.iloc[previous_idx] - 1).dropna()

        # Rank tickers based on their percentage change and select the top 10
        top_10_tickers = pct_change.nlargest(10).index
        
        # Print top performers, their percentage change, and the date range used for calculation
        print(f"Top 10 Performers on {close_prices.index[current_idx].date()} from {close_prices.index[previous_idx].date()} to {close_prices.index[current_idx].date()}:")
        for ticker in top_10_tickers:
            print(f"{ticker}: {pct_change[ticker]*100:.2f}%")
    else:
        # If there is no previous index (first rebalancing), give no allocations
        top_10_tickers = []

    # Create an array of zeros for all tickers
    weights = np.zeros(symbol_wrapper.shape[1])
    
    # Assign 0.1 weight to the top 10 performing tickers
    for ticker in top_10_tickers:
        ticker_index = symbol_wrapper.columns.get_loc(ticker)
        weights[ticker_index] = 0.1

    return weights

# Apply allocations at each rebalancing point
previous_idx = None
for idx in ms_points:
    filled_allocations.iloc[idx] = top_performers_allocate_func(idx, previous_idx)
    previous_idx = idx  # Update previous_idx to the current idx

# Remove rows with NaN values
allocations_from_all_data = filled_allocations[~filled_allocations.isnull().any(axis=1)]

# Display final allocations
#allocations_from_all_data

Top 10 Performers on 2009-04-03 from 2009-01-02 to 2009-04-03:
SIRI: 191.67%
WDC: 72.75%
DXCM: 66.67%
MU: 58.45%
SWKS: 58.14%
SBAC: 52.18%
NFLX: 44.19%
AMD: 44.12%
AMZN: 43.80%
MRVL: 41.49%
Top 10 Performers on 2009-07-02 from 2009-04-03 to 2009-07-02:
VMED: 65.11%
ISRG: 64.08%
BIDU: 54.40%
TCOM: 54.27%
STX: 52.75%
ULTA: 51.42%
FFIV: 46.75%
EXPE: 46.20%
VEON: 41.96%
INCY: 41.00%
Top 10 Performers on 2009-09-30 from 2009-07-02 to 2009-09-30:
UAL: 178.55%
QRTEA: 128.07%
WYNN: 112.18%
INCY: 100.30%
AAL: 91.06%
LULU: 85.56%
PARA: 83.72%
FLEX: 81.75%
MU: 65.32%
ISRG: 65.24%
Top 10 Performers on 2009-12-28 from 2009-09-30 to 2009-12-28:
AMD: 73.67%
AMZN: 49.22%
MELI: 40.64%
INCY: 39.26%
BKNG: 38.25%
UAL: 37.09%
SMCI: 35.11%
LULU: 32.26%
FFIV: 32.07%
AKAM: 31.55%
Top 10 Performers on 2010-03-29 from 2009-12-28 to 2010-03-29:
UAL: 58.15%
INCY: 49.57%
SMCI: 49.17%
PRGO: 47.62%
AAL: 45.82%
BIDU: 42.24%
SIRI: 40.00%
LULU: 36.99%
QRTEA: 35.84%
CCEP: 32.90%
Top 10 Performers on 2010-06-28 from 2010-03-29 to 2010-06-28:
NFLX: 59.15%
AKAM: 41.82%
SIRI: 25.00%
AAL: 24.04%
BIDU: 23.35%
GOLD: 22.75%
NTAP: 22.28%
TMUS: 21.63%
SRCL: 20.95%
MELI: 19.48%
Top 10 Performers on 2010-09-27 from 2010-06-28 to 2010-09-27:
BKNG: 83.66%
EXPE: 49.12%
FOSL: 46.65%
FTNT: 41.21%
FFIV: 40.43%
NFLX: 40.29%
BIDU: 39.47%
AMZN: 35.29%
VMED: 33.27%
ALGN: 31.67%
Top 10 Performers on 2010-12-23 from 2010-09-27 to 2010-12-23:
LULU: 64.64%
NXPI: 64.00%
TSLA: 46.57%
BKR: 40.08%
SIRI: 38.79%
FOSL: 36.51%
SWKS: 35.97%
ON: 33.95%
CHKP: 31.53%
FFIV: 31.36%
Top 10 Performers on 2011-03-24 from 2010-12-23 to 2011-03-24:
MU: 44.84%
NXPI: 40.87%
ULTA: 37.71%
SMCI: 34.38%
BIDU: 33.27%
FTNT: 33.05%
VRTX: 32.55%
CHTR: 30.88%
PARA: 29.74%
NTES: 29.30%
Top 10 Performers on 2011-06-22 from 2011-03-24 to 2011-06-22:
BIIB: 39.57%
FOSL: 31.47%
MNST: 29.47%
EXPE: 28.74%
LULU: 28.63%
ULTA: 28.53%
REGN: 28.52%
MTCH: 24.93%
IAC: 24.93%
INCY: 24.51%
Top 10 Performers on 2011-09-20 from 2011-06-22 to 2011-09-20:
AAPL: 28.16%
MNST: 22.92%
BMRN: 22.59%
REGN: 21.83%
AMZN: 21.72%
GOLD: 20.91%
LULU: 16.42%
DLTR: 15.93%
WYNN: 15.49%
ULTA: 14.13%
Top 10 Performers on 2011-12-19 from 2011-09-20 to 2011-12-19:
ALGN: 46.73%
STX: 33.57%
FFIV: 31.10%
FTNT: 24.09%
VRSN: 22.36%
MELI: 22.06%
ODFL: 21.70%
AKAM: 21.67%
CSGP: 20.88%
KLAC: 18.77%
Top 10 Performers on 2012-03-19 from 2011-12-19 to 2012-03-19:
REGN: 116.82%
SWKS: 94.44%
ILMN: 89.64%
NXPI: 83.87%
STX: 77.14%
NFLX: 70.26%
AMD: 68.31%
LULU: 61.94%
FOSL: 61.58%
MU: 58.35%
Top 10 Performers on 2012-06-18 from 2012-03-19 to 2012-06-18:
AAL: 73.85%
EXPE: 46.59%
VRTX: 38.74%
TRIP: 32.09%
MNST: 31.86%
LOGI: 29.45%
EQIX: 24.53%
ALGN: 24.35%
INCY: 23.22%
ROST: 22.69%
Top 10 Performers on 2012-09-14 from 2012-06-18 to 2012-09-14:
TMUS: 84.23%
FSLR: 70.08%
VEON: 49.37%
URBN: 43.72%
WDC: 34.40%
SIRI: 34.24%
GEN: 29.50%
NXPI: 29.34%
STX: 29.10%
FOSL: 28.34%
Top 10 Performers on 2012-12-12 from 2012-09-14 to 2012-12-12:
NFLX: 49.92%
ASML: 38.65%
BMRN: 31.78%
FSLR: 30.03%
RYAAY: 25.45%
META: 25.36%
GILD: 22.91%
REGN: 22.29%
AAL: 20.61%
TTWO: 19.85%
Top 10 Performers on 2013-03-13 from 2012-12-12 to 2013-03-13:
BMC: 347.37%
NFLX: 112.01%
ENPH: 81.52%
INCY: 46.21%
FANG: 45.98%
UAL: 44.04%
NTES: 42.31%
MU: 41.73%
WDC: 33.10%
VMED: 31.82%
Top 10 Performers on 2013-06-11 from 2013-03-13 to 2013-06-11:
TSLA: 142.36%
FSLR: 94.39%
TCOM: 65.86%
VRTX: 54.25%
AMD: 52.31%
REGN: 43.99%
MU: 34.70%
DXCM: 34.17%
FANG: 33.83%
MNST: 30.32%
Top 10 Performers on 2013-09-09 from 2013-06-11 to 2013-09-09:
INCY: 83.90%
META: 83.27%
TSLA: 70.11%
TCOM: 42.40%
CSGP: 39.46%
BIDU: 37.36%
NFLX: 37.16%
ALGN: 34.34%
NXPI: 29.53%
BMRN: 29.41%
Top 10 Performers on 2013-12-09 from 2013-09-09 to 2013-12-09:
MU: 48.02%
FSLR: 46.63%
LOGI: 44.35%
AAL: 40.81%
SMCI: 30.15%
AMZN: 28.42%
STX: 27.40%
ILMN: 27.33%
BIDU: 25.86%
WYNN: 25.84%
Top 10 Performers on 2014-03-07 from 2013-12-09 to 2014-03-07:
TSLA: 73.88%
ILMN: 66.14%
AAL: 58.62%
ENPH: 48.95%
PANW: 47.77%
META: 42.92%
FANG: 41.74%
INCY: 39.46%
WYNN: 38.94%
DXCM: 38.37%
Top 10 Performers on 2014-06-06 from 2014-03-07 to 2014-06-06:
SWKS: 28.06%
FANG: 26.94%
EXC: 26.55%
AAPL: 22.38%
LRCX: 21.84%
MU: 20.97%
FLEX: 20.77%
EA: 18.62%
CHRW: 17.72%
CHTR: 17.22%
Top 10 Performers on 2014-09-04 from 2014-06-06 to 2014-09-04:
ENPH: 74.03%
STLD: 37.77%
TSLA: 37.41%
SHPG: 37.06%
MELI: 33.38%
MNST: 30.12%
BIDU: 30.09%
GILD: 29.70%
NTES: 27.24%
ISRG: 25.17%
Top 10 Performers on 2014-12-02 from 2014-09-04 to 2014-12-02:
INCY: 43.77%
BMRN: 35.06%
PANW: 34.88%
VRTX: 29.93%
SMCI: 28.17%
DXCM: 25.23%
DLTR: 24.88%
AAL: 24.72%
MNST: 23.36%
VTRS: 23.20%
Top 10 Performers on 2015-03-02 from 2014-12-02 to 2015-03-02:
LULU: 46.53%
AVGO: 40.44%
ON: 39.26%
SWKS: 38.72%
NFLX: 36.31%
NXPI: 32.11%
EA: 31.68%
FSLR: 31.65%
MNST: 28.88%
BIIB: 26.66%
Top 10 Performers on 2015-06-01 from 2015-03-02 to 2015-06-01:
TCOM: 80.84%
NTES: 48.86%
NFLX: 29.73%
VTRS: 26.65%
TSLA: 26.41%
INCY: 23.68%
JD: 23.48%
REGN: 22.79%
PRGO: 22.57%
EQIX: 22.44%
Top 10 Performers on 2015-08-31 from 2015-06-01 to 2015-08-31:
BMC: 1695.48%
DXCM: 30.12%
NFLX: 29.24%
AMZN: 19.02%
GOOGL: 17.95%
CCEP: 16.84%
GOOG: 15.78%
META: 11.38%
CHRW: 9.24%
VRSN: 8.98%
Top 10 Performers on 2015-11-27 from 2015-08-31 to 2015-11-27:
TCOM: 54.55%
NTES: 48.02%
NVDA: 40.17%
BIDU: 39.61%
ADSK: 34.87%
KLAC: 33.83%
AMZN: 31.27%
VRSN: 29.53%
AMD: 28.73%
MSFT: 24.76%
Top 10 Performers on 2016-02-25 from 2015-11-27 to 2016-02-25:
GOLD: 91.28%
MAT: 37.11%
WYNN: 32.92%
SMCI: 31.79%
FSLR: 28.79%
FOSL: 18.79%
EXC: 16.92%
LULU: 16.86%
AEP: 15.24%
XEL: 13.82%
Top 10 Performers on 2016-05-26 from 2016-02-25 to 2016-05-26:
AMD: 114.29%
NVDA: 44.04%
STLD: 37.02%
MELI: 31.81%
WDAY: 31.36%
NTES: 30.98%
ULTA: 30.10%
NXPI: 28.82%
AMZN: 28.78%
FANG: 28.44%
Top 10 Performers on 2016-08-24 from 2016-05-26 to 2016-08-24:
AMD: 70.80%
STX: 46.54%
DXCM: 43.07%
LOGI: 40.90%
NTAP: 40.89%
GEN: 39.28%
NVDA: 35.93%
MU: 29.79%
EBAY: 29.56%
URBN: 28.33%
Top 10 Performers on 2016-11-21 from 2016-08-24 to 2016-11-21:
NVDA: 50.11%
UAL: 44.94%
STLD: 38.32%
WDC: 35.86%
INCY: 31.13%
STX: 28.31%
AAL: 26.05%
MU: 25.66%
AKAM: 23.93%
NFLX: 23.93%
Top 10 Performers on 2017-02-21 from 2016-11-21 to 2017-02-21:
AMD: 56.60%
ENPH: 56.48%
TSLA: 50.33%
CSX: 42.04%
ON: 39.32%
VEON: 33.33%
GOLD: 30.85%
NTES: 25.73%
FSLR: 24.64%
DELL: 24.14%
Top 10 Performers on 2017-05-22 from 2017-02-21 to 2017-05-22:
TTD: 50.03%
MELI: 38.82%
JD: 37.81%
VRTX: 37.42%
IAC: 36.54%
ALGN: 35.58%
WYNN: 30.96%
LRCX: 30.28%
ADSK: 30.07%
BMC: 25.39%
Top 10 Performers on 2017-08-21 from 2017-05-22 to 2017-08-21:
TTWO: 33.23%
FSLR: 26.16%
CHTR: 25.29%
VRTX: 25.28%
ALGN: 21.64%
LULU: 20.06%
PYPL: 19.35%
BIDU: 16.06%
JBHT: 15.85%
RYAAY: 14.68%
Top 10 Performers on 2017-11-16 from 2017-08-21 to 2017-11-16:
ENPH: 230.95%
MU: 56.22%
MTCH: 53.24%
ALGN: 51.76%
ATYR: 48.08%
TEAM: 44.95%
URBN: 40.02%
LRCX: 38.27%
NTAP: 36.97%
ON: 35.81%
Top 10 Performers on 2018-02-14 from 2017-11-16 to 2018-02-14:
FOSL: 122.70%
TEVA: 52.08%
MTCH: 46.33%
MELI: 43.21%
WBD: 42.18%
NFLX: 36.05%
URBN: 35.73%
TRIP: 34.26%
STX: 33.27%
KDP: 32.72%
Top 10 Performers on 2018-05-16 from 2018-02-14 to 2018-05-16:
ENPH: 109.74%
TTD: 71.04%
DXCM: 55.26%
OKTA: 44.43%
MDB: 39.86%
BKR: 39.48%
ALTR: 36.23%
SHPG: 31.19%
MU: 30.03%
PANW: 26.15%
Top 10 Performers on 2018-08-14 from 2018-05-16 to 2018-08-14:
TTD: 64.71%
AMD: 56.16%
MDB: 52.40%
DXCM: 47.25%
ZS: 38.50%
FOSL: 31.62%
IAC: 30.89%
FTNT: 30.27%
MNST: 28.47%
ALGN: 28.02%
Top 10 Performers on 2018-11-12 from 2018-08-14 to 2018-11-12:
ULTA: 30.92%
SBUX: 29.13%
WBD: 22.67%
KDP: 21.55%
GOLD: 21.19%
WBA: 20.56%
TSCO: 18.47%
GEN: 17.44%
CCEP: 15.80%
TRIP: 15.52%
Top 10 Performers on 2019-02-11 from 2018-11-12 to 2019-02-11:
PDD: 55.28%
OKTA: 51.83%
MTCH: 48.12%
TEAM: 47.70%
WDAY: 42.98%
ENPH: 42.36%
MDB: 42.19%
TTD: 34.23%
ON: 32.14%
SMCI: 31.15%
Top 10 Performers on 2019-05-13 from 2019-02-11 to 2019-05-13:
ENPH: 77.10%
QCOM: 66.96%
MELI: 54.78%
ZS: 40.13%
MRNA: 34.45%
CDNS: 31.59%
MDB: 28.75%
XRAY: 27.92%
SMCI: 27.18%
ALGN: 26.81%
Top 10 Performers on 2019-08-09 from 2019-05-13 to 2019-08-09:
ENPH: 132.65%
TTD: 53.85%
GOLD: 47.86%
OKTA: 34.12%
DXCM: 33.71%
AMD: 30.30%
ZM: 29.86%
CSGP: 29.72%
TTWO: 28.86%
WDC: 27.66%
Top 10 Performers on 2019-11-06 from 2019-08-09 to 2019-11-06:
PDD: 92.43%
DOCU: 45.78%
URBN: 43.76%
LRCX: 41.76%
ALGN: 39.73%
RYAAY: 39.58%
TSLA: 38.96%
SRCL: 38.87%
NVDA: 34.80%
STX: 30.43%
Top 10 Performers on 2020-02-04 from 2019-11-06 to 2020-02-04:
TSLA: 171.62%
ENPH: 102.75%
ATYR: 60.00%
DXCM: 59.16%
TTD: 55.92%
TEVA: 48.89%
MELI: 46.98%
PTON: 45.40%
DDOG: 43.98%
SMCI: 41.11%
Top 10 Performers on 2020-05-05 from 2020-02-04 to 2020-05-05:
MRNA: 136.42%
ZM: 68.81%
REGN: 61.34%
GOLD: 56.96%
DXCM: 49.48%
INCY: 33.76%
PDD: 33.44%
DOCU: 33.32%
QGEN: 25.93%
GEN: 23.56%
Top 10 Performers on 2020-08-03 from 2020-05-05 to 2020-08-03:
DOCU: 106.93%
DDOG: 105.30%
PTON: 100.66%
PDD: 97.11%
TSLA: 93.31%
MELI: 88.85%
ZS: 86.13%
ZM: 85.06%
IAC: 78.65%
PARA: 70.21%
Top 10 Performers on 2020-11-02 from 2020-08-03 to 2020-11-02:
FOSL: 71.04%
ENPH: 69.63%
ZM: 69.03%
ALGN: 59.54%
PTON: 56.08%
FSLR: 46.10%
TSLA: 34.85%
URBN: 31.80%
JD: 27.57%
NCLH: 23.81%
Top 10 Performers on 2021-01-29 from 2020-11-02 to 2021-01-29:
MRNA: 158.02%
FOSL: 153.05%
LCID: 137.59%
QRTEA: 111.91%
FANG: 106.98%
TSLA: 98.13%
WBD: 96.12%
PDD: 80.87%
ENPH: 75.62%
BIDU: 75.32%
Top 10 Performers on 2021-04-30 from 2021-01-29 to 2021-04-30:
STLD: 59.05%
TRIP: 52.18%
FANG: 44.99%
EXPE: 42.01%
STX: 41.66%
FTNT: 41.09%
AMAT: 37.53%
NCLH: 37.09%
UAL: 36.03%
CDW: 35.79%
Top 10 Performers on 2021-07-29 from 2021-04-30 to 2021-07-29:
MRNA: 93.29%
DOCU: 35.09%
FTNT: 34.27%
MRVL: 33.54%
EBAY: 31.98%
NVDA: 31.03%
ENPH: 30.74%
DDOG: 29.68%
IDXX: 28.26%
INTU: 27.65%
Top 10 Performers on 2021-10-27 from 2021-07-29 to 2021-10-27:
BMC: 120.55%
ATYR: 88.65%
TEAM: 54.76%
TSLA: 53.22%
DDOG: 41.23%
MDB: 37.54%
FANG: 36.04%
FSLR: 31.63%
ZS: 30.83%
NFLX: 28.91%
Top 10 Performers on 2022-01-24 from 2021-10-27 to 2022-01-24:
LCID: 39.71%
QCOM: 30.12%
VRTX: 26.94%
DLTR: 26.47%
ON: 24.22%
MU: 21.69%
BMRN: 20.22%
INCY: 15.96%
SMCI: 15.94%
KLAC: 15.13%
Top 10 Performers on 2022-04-25 from 2022-01-24 to 2022-04-25:
STLD: 63.97%
CEG: 45.97%
DLTR: 28.53%
CRWD: 28.28%
UAL: 23.94%
ENPH: 23.03%
EXC: 22.90%
AAL: 21.76%
TMUS: 20.78%
KHC: 19.53%
Top 10 Performers on 2022-07-25 from 2022-04-25 to 2022-07-25:
PDD: 57.89%
ENPH: 38.67%
TCOM: 24.10%
SMCI: 22.67%
PRGO: 22.02%
BIDU: 20.31%
JD: 20.20%
SNPS: 16.07%
QCOM: 12.81%
CDNS: 10.96%
Top 10 Performers on 2022-10-24 from 2022-07-25 to 2022-10-24:
FSLR: 68.00%
CEG: 59.64%
STLD: 38.16%
BIIB: 32.30%
FANG: 30.72%
NCLH: 29.53%
NFLX: 29.26%
TRIP: 27.40%
GFS: 26.77%
REGN: 25.52%
Top 10 Performers on 2023-01-19 from 2022-10-24 to 2023-01-19:
PDD: 102.92%
TCOM: 84.58%
VEON: 80.65%
WYNN: 75.00%
JD: 62.08%
BIDU: 60.73%
NTES: 59.56%
FOSL: 50.72%
PTON: 49.14%
RYAAY: 46.32%
Top 10 Performers on 2023-04-20 from 2023-01-19 to 2023-04-20:
NVDA: 61.70%
META: 56.50%
SMCI: 52.43%
ALGN: 49.13%
VEON: 44.36%
TTD: 40.58%
FTNT: 38.17%
TIGO: 37.30%
ALTR: 37.17%
PANW: 36.64%
Top 10 Performers on 2023-07-19 from 2023-04-20 to 2023-07-19:
SMCI: 181.15%
RIVN: 101.05%
MDB: 90.36%
TSLA: 78.70%
NVDA: 73.71%
DDOG: 70.75%
NCLH: 67.25%
MRVL: 66.45%
ZS: 60.25%
META: 48.31%
Top 10 Performers on 2023-10-17 from 2023-07-19 to 2023-10-17:
PDD: 39.37%
DELL: 25.92%
CEG: 24.00%
AMGN: 23.56%
OKTA: 22.45%
FANG: 21.98%
CRWD: 18.74%
CHTR: 16.50%
STX: 16.41%
REGN: 16.39%
Top 10 Performers on 2024-01-16 from 2023-10-17 to 2024-01-16:
DXCM: 54.63%
CRWD: 52.98%
AMD: 50.98%
DOCU: 47.48%
QRTEA: 47.37%
EXPE: 46.38%
DASH: 37.08%
DDOG: 36.92%
PDD: 36.54%
RYAAY: 35.44%
Top 10 Performers on 2024-04-15 from 2024-01-16 to 2024-04-15:
SMCI: 170.52%
ARM: 78.62%
CEG: 66.14%
NVDA: 52.54%
DELL: 48.81%
MU: 43.58%
FANG: 38.15%
META: 36.28%
ASML: 35.38%
WDC: 34.85%
Top 10 Performers on 2024-07-15 from 2024-04-15 to 2024-07-15:
RIVN: 108.33%
FOSL: 56.63%
TSLA: 56.45%
NVDA: 49.36%
LCID: 48.56%
ARM: 45.14%
AAPL: 35.92%
AVGO: 31.20%
STX: 30.74%
TEVA: 29.10%

symbol,AAL,AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AKAM,ALGN,...,WBA,WBD,WDAY,WDC,WTW,WYNN,XEL,XRAY,ZM,ZS
Date,,,,,,,,,,,,,,,,,,,,,
2009-01-02 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-04-03 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0
2009-07-02 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-09-30 04:00:00+00:00,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0
2009-12-28 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-07-19 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1
2023-10-17 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-16 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-04-15 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0
2024-07-15 04:00:00+00:00,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

<h2>GENERATING ALLOCATIONS USING THE NASDAQ 100 LIST</h2>
ONLY ALLOW TRADES TICKERS THAT WAS IN THE NASDAQ 100 LIST AT THE DATE WHEN REBALICING WAS DONE

In [106]:
import numpy as np
import pandas as pd
import pytz

# Load Nasdaq 100 index data
nasdaq100index = pd.read_csv('./data/nasdaq_100_index.csv')

# Convert Date column to datetime, localize to UTC and set time to midnight (00:00:00)
nasdaq100index['Date'] = pd.to_datetime(nasdaq100index['Date']).dt.tz_localize('UTC').dt.normalize()

# Get the close prices data
close_prices = data.get("Close")

# Define the allocation function to calculate performance between consecutive points
def top_performers_allocate_func(current_idx, previous_idx):
    # Get the current date from the close_prices index
    current_date = close_prices.index[current_idx].normalize()

    # Check if current_date exists in nasdaq100index['Date']
    matching_row = nasdaq100index[nasdaq100index['Date'] == current_date]
    if matching_row.empty:
        print(f"No tickers found for the date {current_date}.")
        return np.zeros(symbol_wrapper.shape[1])  # Return empty allocation if no tickers found

    # Get the tickers for the current date
    available_tickers = matching_row.iloc[:, 1:].values.flatten()
    available_tickers = available_tickers[~pd.isnull(available_tickers)]  # Remove NaN entries

    # Filter available_tickers to only those present in close_prices columns
    available_tickers_in_prices = [ticker for ticker in available_tickers if ticker in close_prices.columns]

    if len(available_tickers_in_prices) == 0:
        print(f"No available tickers found in close prices on {current_date}.")
        return np.zeros(symbol_wrapper.shape[1])  # Return empty allocation if no tickers available

    # Filter the close_prices dataframe for available tickers on the current date
    close_prices_filtered = close_prices[available_tickers_in_prices]

    # Calculate the percentage change between current and previous idx
    if previous_idx is not None:
        # Percentage change for each ticker
        pct_change = (close_prices_filtered.iloc[current_idx] / close_prices_filtered.iloc[previous_idx] - 1).dropna()

        # Rank tickers based on their percentage change and select the top 10
        top_10_tickers = pct_change.nlargest(10).index
        
        if top_10_tickers.empty:
            print(f"No top performers found for the date {current_date}.")
            return np.zeros(symbol_wrapper.shape[1])  # Return empty allocation if no top tickers found

        # Print top performers, their percentage change, and the date range used for calculation
        print(f"Top 10 Performers on {close_prices.index[current_idx].date()} from {close_prices.index[previous_idx].date()} to {close_prices.index[current_idx].date()}:")
        for ticker in top_10_tickers:
            print(f"{ticker}: {pct_change[ticker]*100:.2f}%")
    else:
        # If there is no previous index (first rebalancing), give no allocations
        top_10_tickers = []

    # Create an array of zeros for all tickers
    weights = np.zeros(symbol_wrapper.shape[1])
    
    # Assign 0.1 weight to the top 10 performing tickers
    for ticker in top_10_tickers:
        ticker_index = symbol_wrapper.columns.get_loc(ticker)
        weights[ticker_index] = 0.1

    return weights

# Apply allocations at each rebalancing point
previous_idx = None
for idx in ms_points:
    filled_allocations.iloc[idx] = top_performers_allocate_func(idx, previous_idx)
    previous_idx = idx  # Update previous_idx to the current idx

# Remove rows with NaN values
allocations_from_only_nasdaq100_index = filled_allocations[~filled_allocations.isnull().any(axis=1)]

# Display final allocations
#print(allocations_from_only_nasdaq100_index)

No tickers found for the date 2009-01-02 00:00:00+00:00.
No tickers found for the date 2009-04-03 00:00:00+00:00.
No tickers found for the date 2009-07-02 00:00:00+00:00.
No tickers found for the date 2009-09-30 00:00:00+00:00.
Top 10 Performers on 2009-12-28 from 2009-09-30 to 2009-12-28:
AMZN: 49.22%
BKNG: 38.25%
NTAP: 27.47%
MRVL: 26.99%
GOOG: 25.62%
GOOGL: 25.62%
VMED: 25.43%
MSFT: 21.73%
CHKP: 20.81%
ORCL: 20.11%
Top 10 Performers on 2010-03-29 from 2009-12-28 to 2010-03-29:
BIDU: 42.24%
QRTEA: 35.84%
WYNN: 30.50%
ILMN: 28.65%
GRMN: 26.67%
ROST: 25.33%
HOLX: 25.15%
VTRS: 22.36%
PCAR: 20.03%
CTAS: 17.68%
Top 10 Performers on 2010-06-28 from 2010-03-29 to 2010-06-28:
BIDU: 23.35%
NTAP: 22.28%
SRCL: 20.95%
ORLY: 16.40%
AAPL: 15.45%
ILMN: 14.95%
WBD: 11.43%
WYNN: 11.10%
LRCX: 9.68%
VRSN: 8.07%
Top 10 Performers on 2010-09-27 from 2010-06-28 to 2010-09-27:
BKNG: 83.66%
EXPE: 49.12%
BIDU: 39.47%
AMZN: 35.29%
VMED: 33.27%
QCOM: 31.65%
EXPD: 25.72%
INTU: 24.78%
NTAP: 24.13%
FSLR: 24.05%
Top 10 Performers on 2010-12-23 from 2010-09-27 to 2010-12-23:
CHKP: 31.53%
FFIV: 31.36%
FLEX: 30.55%
ILMN: 28.45%
STX: 28.14%
WYNN: 27.60%
LRCX: 26.20%
SBUX: 25.31%
NVDA: 24.33%
ADSK: 23.66%
Top 10 Performers on 2011-03-24 from 2010-12-23 to 2011-03-24:
MU: 44.84%
BIDU: 33.27%
VRTX: 32.55%
NVDA: 28.89%
ISRG: 25.56%
EA: 24.47%
NFLX: 24.14%
WYNN: 20.62%
KLAC: 19.84%
GILD: 15.94%
Top 10 Performers on 2011-06-22 from 2011-03-24 to 2011-06-22:
BIIB: 39.57%
EXPE: 28.74%
DLTR: 18.11%
VMED: 15.24%
EA: 13.61%
ILMN: 13.18%
ROST: 12.53%
AMZN: 12.00%
COST: 11.99%
MDLZ: 11.84%
Top 10 Performers on 2011-09-20 from 2011-06-22 to 2011-09-20:
AAPL: 28.16%
AMZN: 21.72%
DLTR: 15.93%
WYNN: 15.49%
GOOG: 12.24%
GOOGL: 12.24%
BIDU: 12.06%
BKNG: 11.77%
EBAY: 11.52%
ORLY: 10.79%
Top 10 Performers on 2011-12-19 from 2011-09-20 to 2011-12-19:
STX: 33.57%
FFIV: 31.10%
VRSN: 22.36%
AKAM: 21.67%
KLAC: 18.77%
GRMN: 15.70%
TEVA: 14.50%
ROST: 14.30%
FAST: 13.77%
GOOGL: 13.76%
Top 10 Performers on 2012-03-19 from 2011-12-19 to 2012-03-19:
STX: 77.14%
NFLX: 70.26%
FOSL: 61.58%
MU: 58.35%
AAPL: 57.27%
BKNG: 51.60%
AKAM: 39.46%
AVGO: 38.63%
ADSK: 37.09%
PCAR: 33.98%
Top 10 Performers on 2012-06-18 from 2012-03-19 to 2012-06-18:
EXPE: 46.59%
VRTX: 38.74%
MNST: 31.86%
ROST: 22.69%
DLTR: 20.27%
AMZN: 20.02%
BIIB: 18.33%
ORLY: 13.37%
VRSN: 13.02%
EBAY: 12.44%
Top 10 Performers on 2012-09-14 from 2012-06-18 to 2012-09-14:
SIRI: 34.24%
GEN: 29.50%
STX: 29.10%
FOSL: 28.34%
VMED: 27.35%
AKAM: 24.58%
GOOGL: 24.32%
GOOG: 24.32%
GILD: 23.52%
ORCL: 21.75%
Top 10 Performers on 2012-12-12 from 2012-09-14 to 2012-12-12:
NFLX: 49.92%
META: 25.36%
GILD: 22.91%
VMED: 19.50%
ORLY: 15.49%
VTRS: 14.57%
SIRI: 12.55%
FI: 11.77%
AMGN: 11.30%
EXPE: 8.64%
Top 10 Performers on 2013-03-13 from 2012-12-12 to 2013-03-13:
BMC: 347.37%
MU: 41.73%
WDC: 33.10%
VMED: 31.82%
GEN: 30.88%
PARA: 27.56%
WBD: 27.31%
STX: 27.24%
VRTX: 24.90%
AMAT: 23.71%
Top 10 Performers on 2013-06-11 from 2013-03-13 to 2013-06-11:
VRTX: 54.25%
REGN: 43.99%
MU: 34.70%
MNST: 30.32%
WDC: 28.76%
BIIB: 26.61%
AKAM: 26.49%
MSFT: 25.66%
STX: 25.62%
ROST: 15.77%
Top 10 Performers on 2013-09-09 from 2013-06-11 to 2013-09-09:
META: 83.27%
TSLA: 70.11%
BIDU: 37.36%
NFLX: 37.16%
GRMN: 24.29%
MU: 21.94%
CTSH: 21.56%
GILD: 19.49%
BKNG: 18.72%
VTRS: 18.59%
Top 10 Performers on 2013-12-09 from 2013-09-09 to 2013-12-09:
MU: 48.02%
AMZN: 28.42%
STX: 27.40%
BIDU: 25.86%
WYNN: 25.84%
EXPE: 25.70%
BIIB: 25.05%
ADSK: 24.08%
MSFT: 23.20%
AVGO: 22.90%
Top 10 Performers on 2014-03-07 from 2013-12-09 to 2014-03-07:
TSLA: 73.88%
ILMN: 66.14%
META: 42.92%
WYNN: 38.94%
AKAM: 37.54%
FFIV: 34.75%
NXPI: 34.47%
AVGO: 33.09%
TRIP: 27.47%
NFLX: 26.06%
Top 10 Performers on 2014-06-06 from 2014-03-07 to 2014-06-06:
AAPL: 22.38%
MU: 20.97%
CHRW: 17.72%
CHTR: 17.22%
EXPD: 16.33%
INTC: 15.31%
CSCO: 15.24%
MAR: 15.10%
AVGO: 14.64%
STX: 13.58%
Top 10 Performers on 2014-09-04 from 2014-06-06 to 2014-09-04:
TSLA: 37.41%
MNST: 30.12%
BIDU: 30.09%
GILD: 29.70%
ISRG: 25.17%
INTC: 24.75%
VRTX: 24.57%
META: 21.52%
AVGO: 20.68%
AMGN: 17.70%
Top 10 Performers on 2014-12-02 from 2014-09-04 to 2014-12-02:
VRTX: 29.93%
DLTR: 24.88%
MNST: 23.36%
VTRS: 23.20%
AMGN: 23.13%
LBTYA: 19.88%
REGN: 19.64%
KDP: 18.35%
CTSH: 18.33%
ROST: 17.45%
Top 10 Performers on 2015-03-02 from 2014-12-02 to 2015-03-02:
AVGO: 40.44%
NFLX: 36.31%
NXPI: 32.11%
EA: 31.68%
MNST: 28.88%
BIIB: 26.66%
TRIP: 18.95%
AMZN: 18.19%
SBUX: 17.67%
ROST: 17.66%
Top 10 Performers on 2015-06-01 from 2015-03-02 to 2015-06-01:
NFLX: 29.73%
VTRS: 26.65%
TSLA: 26.41%
REGN: 22.79%
ADI: 15.70%
VEON: 15.44%
AVGO: 13.98%
NXPI: 12.47%
VOD: 12.23%
AMZN: 11.74%
Top 10 Performers on 2015-08-31 from 2015-06-01 to 2015-08-31:
NFLX: 29.24%
AMZN: 19.02%
GOOGL: 17.95%
GOOG: 15.78%
META: 11.38%
CHRW: 9.24%
MNST: 8.88%
ORLY: 7.90%
BKNG: 7.03%
FI: 5.85%
Top 10 Performers on 2015-11-27 from 2015-08-31 to 2015-11-27:
NVDA: 40.17%
BIDU: 39.61%
ADSK: 34.87%
KLAC: 33.83%
AMZN: 31.27%
MSFT: 24.76%
PAYX: 22.03%
INTC: 21.59%
GOOG: 21.35%
TXN: 21.08%
Top 10 Performers on 2016-02-25 from 2015-11-27 to 2016-02-25:
MAT: 37.11%
FAST: 12.64%
DLTR: 9.62%
HSIC: 8.12%
ISRG: 7.71%
ROST: 7.60%
QCOM: 6.39%
PYPL: 4.43%
TMUS: 3.98%
FI: 3.90%
Top 10 Performers on 2016-05-26 from 2016-02-25 to 2016-05-26:
NVDA: 44.04%
NTES: 30.98%
ULTA: 30.10%
NXPI: 28.82%
AMZN: 28.78%
AMAT: 26.17%
TSLA: 20.11%
CHTR: 19.67%
ADSK: 17.58%
LRCX: 16.56%
Top 10 Performers on 2016-08-24 from 2016-05-26 to 2016-08-24:
STX: 46.54%
NTAP: 40.89%
GEN: 39.28%
NVDA: 35.93%
MU: 29.79%
EBAY: 29.56%
ULTA: 28.21%
AMAT: 25.59%
MCHP: 21.17%
NTES: 19.39%
Top 10 Performers on 2016-11-21 from 2016-08-24 to 2016-11-21:
NVDA: 50.11%
WDC: 35.86%
INCY: 31.13%
STX: 28.31%
AAL: 26.05%
MU: 25.66%
AKAM: 23.93%
NFLX: 23.93%
CSX: 22.30%
ADSK: 19.55%
Top 10 Performers on 2017-02-21 from 2016-11-21 to 2017-02-21:
TSLA: 50.33%
CSX: 42.04%
NTES: 25.73%
AVGO: 23.98%
WDC: 23.32%
CHTR: 23.12%
AAPL: 22.88%
SWKS: 22.72%
MU: 21.96%
NCLH: 21.75%
Top 10 Performers on 2017-05-22 from 2017-02-21 to 2017-05-22:
JD: 37.81%
VRTX: 37.42%
WYNN: 30.96%
LRCX: 30.28%
ADSK: 30.07%
NVDA: 25.35%
REGN: 24.05%
EA: 23.82%
AMAT: 22.28%
ISRG: 21.84%
Top 10 Performers on 2017-08-21 from 2017-05-22 to 2017-08-21:
CHTR: 25.29%
VRTX: 25.28%
PYPL: 19.35%
BIDU: 16.06%
JBHT: 15.85%
NVDA: 14.58%
GILD: 13.71%
BIIB: 13.24%
META: 13.18%
MNST: 12.45%
Top 10 Performers on 2017-11-16 from 2017-08-21 to 2017-11-16:
MU: 56.22%
LRCX: 38.27%
AMAT: 33.86%
NVDA: 33.08%
INTC: 31.50%
PYPL: 30.81%
QCOM: 28.59%
DLTR: 27.45%
XRAY: 27.45%
STX: 26.73%
Top 10 Performers on 2018-02-14 from 2017-11-16 to 2018-02-14:
MELI: 43.21%
NFLX: 36.05%
STX: 33.27%
AMZN: 27.59%
LBTYA: 22.33%
ROST: 20.41%
ESRX: 19.98%
EBAY: 19.15%
CSCO: 18.18%
MAR: 17.08%
Top 10 Performers on 2018-05-16 from 2018-02-14 to 2018-05-16:
SHPG: 31.19%
MU: 30.03%
ADSK: 23.66%
NFLX: 23.38%
ULTA: 21.89%
INTC: 21.10%
ILMN: 20.50%
BIDU: 20.42%
ADBE: 20.42%
WYNN: 17.73%
Top 10 Performers on 2018-08-14 from 2018-05-16 to 2018-08-14:
MNST: 28.47%
ALGN: 28.02%
ILMN: 22.81%
BIIB: 22.07%
IDXX: 22.04%
TSLA: 21.35%
AMZN: 20.94%
REGN: 20.78%
ORLY: 19.17%
MELI: 19.13%
Top 10 Performers on 2018-11-12 from 2018-08-14 to 2018-11-12:
ULTA: 30.92%
SBUX: 29.13%
WBA: 20.56%
GEN: 17.44%
ESRX: 14.19%
ROST: 9.86%
QRTEA: 8.70%
AVGO: 8.69%
HSIC: 8.43%
ORLY: 8.09%
Top 10 Performers on 2019-02-11 from 2018-11-12 to 2019-02-11:
WDAY: 42.98%
TCOM: 29.16%
MCHP: 28.34%
INCY: 27.60%
WYNN: 26.54%
AVGO: 24.59%
LRCX: 23.95%
AMAT: 23.01%
EBAY: 22.89%
ADI: 21.49%
Top 10 Performers on 2019-05-13 from 2019-02-11 to 2019-05-13:
QCOM: 66.96%
MELI: 54.78%
CDNS: 31.59%
ALGN: 26.81%
MSFT: 17.70%
IDXX: 17.41%
SNPS: 17.22%
COST: 16.22%
JD: 16.06%
TCOM: 15.36%
Top 10 Performers on 2019-08-09 from 2019-05-13 to 2019-08-09:
AMD: 30.30%
TTWO: 28.86%
WDC: 27.66%
MELI: 27.08%
FI: 26.32%
SBUX: 26.06%
KLAC: 25.92%
CTAS: 21.67%
AMAT: 21.24%
GEN: 20.59%
Top 10 Performers on 2019-11-06 from 2019-08-09 to 2019-11-06:
LRCX: 41.76%
ALGN: 39.73%
TSLA: 38.96%
NVDA: 34.80%
AAPL: 27.99%
KLAC: 27.48%
SWKS: 27.35%
KHC: 27.03%
INTC: 25.96%
FAST: 25.65%
Top 10 Performers on 2020-02-04 from 2019-11-06 to 2020-02-04:
TSLA: 171.62%
MELI: 46.98%
AMD: 37.63%
ADSK: 34.60%
ANSS: 32.23%
WDC: 28.39%
NFLX: 27.87%
ADBE: 27.61%
MSFT: 25.46%
CPRT: 25.40%
Top 10 Performers on 2020-05-05 from 2020-02-04 to 2020-05-05:
ZM: 68.81%
REGN: 61.34%
DXCM: 49.48%
INCY: 33.76%
NVDA: 18.93%
GILD: 18.51%
NFLX: 15.09%
VRTX: 13.63%
AMZN: 13.08%
EA: 11.71%
Top 10 Performers on 2020-08-03 from 2020-05-05 to 2020-08-03:
DOCU: 106.93%
TSLA: 93.31%
MELI: 88.85%
ZM: 85.06%
LRCX: 63.54%
MRNA: 58.05%
PYPL: 57.12%
LULU: 50.58%
NVDA: 50.00%
JD: 49.65%
Top 10 Performers on 2020-11-02 from 2020-08-03 to 2020-11-02:
ZM: 69.03%
ALGN: 59.54%
TSLA: 34.85%
JD: 27.57%
CPRT: 21.56%
ADP: 20.88%
EXPE: 18.46%
CSX: 16.62%
NXPI: 15.59%
PAYX: 15.35%
Top 10 Performers on 2021-01-29 from 2020-11-02 to 2021-01-29:
MRNA: 158.02%
TSLA: 98.13%
PDD: 80.87%
BIDU: 75.32%
AMAT: 60.73%
MU: 57.45%
MELI: 46.36%
ASML: 46.26%
ILMN: 45.60%
WBA: 42.07%
Top 10 Performers on 2021-04-30 from 2021-01-29 to 2021-04-30:
AMAT: 37.53%
CDW: 35.79%
GOOG: 31.29%
ORLY: 29.95%
GOOGL: 28.79%
LRCX: 28.52%
MAR: 27.69%
BKNG: 26.83%
META: 25.84%
KHC: 24.48%
Top 10 Performers on 2021-07-29 from 2021-04-30 to 2021-07-29:
MRNA: 93.29%
DOCU: 35.09%
MRVL: 33.54%
EBAY: 31.98%
NVDA: 31.03%
IDXX: 28.26%
INTU: 27.65%
AMD: 26.13%
ILMN: 25.15%
BIIB: 23.13%
Top 10 Performers on 2021-10-27 from 2021-07-29 to 2021-10-27:
TEAM: 54.76%
TSLA: 53.22%
NFLX: 28.91%
NVDA: 24.38%
DXCM: 22.47%
WDAY: 20.35%
AMD: 18.78%
INTU: 16.82%
COST: 15.01%
CDNS: 13.24%
Top 10 Performers on 2022-01-24 from 2021-10-27 to 2022-01-24:
LCID: 39.71%
QCOM: 30.12%
VRTX: 26.94%
DLTR: 26.47%
MU: 21.69%
KLAC: 15.13%
LRCX: 12.57%
MDLZ: 12.55%
WBA: 12.24%
KDP: 12.17%
Top 10 Performers on 2022-04-25 from 2022-01-24 to 2022-04-25:
CEG: 45.97%
DLTR: 28.53%
CRWD: 28.28%
EXC: 22.90%
TMUS: 20.78%
KHC: 19.53%
PANW: 18.94%
VRTX: 18.29%
AZN: 17.70%
MAR: 17.17%
Top 10 Performers on 2022-07-25 from 2022-04-25 to 2022-07-25:
PDD: 57.89%
BIDU: 20.31%
JD: 20.20%
SNPS: 16.07%
QCOM: 12.81%
CDNS: 10.96%
MNST: 10.57%
MRNA: 10.16%
NTES: 9.89%
KLAC: 6.21%
Top 10 Performers on 2022-10-24 from 2022-07-25 to 2022-10-24:
CEG: 59.64%
BIIB: 32.30%
NFLX: 29.26%
REGN: 25.52%
DXCM: 19.82%
GILD: 14.87%
ORLY: 12.15%
ABNB: 10.90%
ILMN: 10.56%
VRTX: 9.45%
Top 10 Performers on 2023-01-19 from 2022-10-24 to 2023-01-19:
PDD: 102.92%
JD: 62.08%
MRNA: 43.12%
IDXX: 37.74%
KLAC: 36.59%
ASML: 33.65%
ROST: 33.26%
NVDA: 33.10%
MELI: 29.69%
BKNG: 28.02%
Top 10 Performers on 2023-04-20 from 2023-01-19 to 2023-04-20:
NVDA: 61.70%
META: 56.50%
ALGN: 49.13%
FTNT: 38.17%
PANW: 36.64%
AMD: 33.08%
ANSS: 30.21%
CRWD: 30.09%
TSLA: 28.17%
CPRT: 26.94%
Top 10 Performers on 2023-07-19 from 2023-04-20 to 2023-07-19:
TSLA: 78.70%
NVDA: 73.71%
DDOG: 70.75%
MRVL: 66.45%
ZS: 60.25%
META: 48.31%
NFLX: 46.79%
SIRI: 44.57%
AVGO: 43.15%
TTD: 41.93%
Top 10 Performers on 2023-10-17 from 2023-07-19 to 2023-10-17:
PDD: 39.37%
CEG: 24.00%
AMGN: 23.56%
FANG: 21.98%
CRWD: 18.74%
CHTR: 16.50%
REGN: 16.39%
GOOG: 14.83%
GOOGL: 14.50%
INTU: 7.82%
Top 10 Performers on 2024-01-16 from 2023-10-17 to 2024-01-16:
DXCM: 54.63%
CRWD: 52.98%
AMD: 50.98%
DASH: 37.08%
DDOG: 36.92%
PDD: 36.54%
NFLX: 35.29%
MELI: 34.82%
ZS: 34.76%
ISRG: 31.58%
Top 10 Performers on 2024-04-15 from 2024-01-16 to 2024-04-15:
CEG: 66.14%
NVDA: 52.54%
MU: 43.58%
FANG: 38.15%
META: 36.28%
ASML: 35.38%
AMAT: 33.99%
DASH: 27.76%
LRCX: 27.04%
TTD: 27.02%
Top 10 Performers on 2024-07-15 from 2024-04-15 to 2024-07-15:
TSLA: 56.45%
NVDA: 49.36%
ARM: 45.14%
AAPL: 35.92%
AVGO: 31.20%
KLAC: 26.73%
CHTR: 26.35%
CRWD: 26.00%
ADI: 25.42%
PANW: 25.27%

In [109]:
# for 181 tickers
allocations_from_all_data

symbol,AAL,AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AKAM,ALGN,...,WBA,WBD,WDAY,WDC,WTW,WYNN,XEL,XRAY,ZM,ZS
Date,,,,,,,,,,,,,,,,,,,,,
2009-01-02 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-04-03 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0
2009-07-02 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-09-30 04:00:00+00:00,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0
2009-12-28 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-07-19 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1
2023-10-17 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-16 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-04-15 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0
2024-07-15 04:00:00+00:00,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [108]:
allocations_from_only_nasdaq100_index

symbol,AAL,AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AKAM,ALGN,...,WBA,WBD,WDAY,WDC,WTW,WYNN,XEL,XRAY,ZM,ZS
Date,,,,,,,,,,,,,,,,,,,,,
2009-01-02 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-04-03 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-07-02 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-09-30 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-12-28 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-07-19 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1
2023-10-17 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-16 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1
2024-04-15 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-07-15 04:00:00+00:00,0.0,0.1,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Download QQQ ticker data for benchmark purpouse

In [104]:
import yfinance as yf
data_qqq_close = vbt.YFData.pull("QQQ", start=FROMDATE, end=TODATE, missing_columns="drop").get("Close")

data_qqq_close

# Get the first and last values of the QQQ data
first_value = data_qqq_close.iloc[0]
last_value = data_qqq_close.iloc[-1]

# Calculate the percentage return
qqq_return_percentage = (last_value - first_value) / first_value * 100

# Print the percentage return
print(f"QQQ return from {FROMDATE} to {TODATE}: {qqq_return_percentage:.2f}%")

QQQ return from 2009-01-01 00:00:00+00:00 to 2024-10-10 00:00:00+00:00: 1726.62%

Run Portfolio Analysis - allocations_from_all_data

In [105]:
pf_allocations_from_all_data = vbt.Portfolio.from_orders(
    close=data.get("Close"),
    size=allocations_from_all_data,
    size_type="targetpercent",
    init_cash=1_000_000,  # Set initial capital to 1M USD
    slippage=0.0005,  # 0.05% slippage (as a decimal fraction)
    fees=0.0005,  # 0.05% commission (as a decimal fraction)
    group_by=True,
    cash_sharing=True,
    call_seq="auto"
)

# Display portfolio statistics
pf_allocations_from_all_data.stats()

Start Index                    2009-01-02 05:00:00+00:00
End Index                      2024-10-09 04:00:00+00:00
Total Duration                        3969 days 00:00:00
Start Value                                    1000000.0
Min Value                                   966897.91753
Max Value                               120984213.562449
End Value                                38733439.950954
Total Return [%]                             3773.343995
Benchmark Return [%]                         2099.588672
Position Coverage [%]                          98.412698
Max Gross Exposure [%]                             100.0
Max Drawdown [%]                               79.709136
Max Drawdown Duration                  729 days 00:00:00
Total Orders                                        1168
Total Fees Paid                             784031.69774
Total Trades                                         626
Win Rate [%]                                   63.902439
Best Trade [%]                                 316.53531
Worst Trade [%]                               -53.965342
Avg Winning Trade [%]                          32.168258
Avg Losing Trade [%]                          -13.821044
Avg Winning Trade Duration    76 days 04:12:49.465648855
Avg Losing Trade Duration     62 days 21:17:50.270270270
Profit Factor                                   1.708467
Expectancy                                  61108.403825
Sharpe Ratio                                    0.703305
Calmar Ratio                                    0.501488
Omega Ratio                                     1.255643
Sortino Ratio                                    1.62996
Name: group, dtype: object

In [92]:
pf_allocations_from_all_data.value.vbt.lineplot()

FigureWidget({
    'data': [{'mode': 'lines',
              'name': 'group',
              'showlegend': True,
              'type': 'scatter',
              'uid': '57d883dc-a66f-40ab-9027-bc73245ca6d9',
              'x': array([datetime.datetime(2009, 1, 2, 5, 0, tzinfo=datetime.timezone.utc),
                          datetime.datetime(2009, 1, 5, 5, 0, tzinfo=datetime.timezone.utc),
                          datetime.datetime(2009, 1, 6, 5, 0, tzinfo=datetime.timezone.utc), ...,
                          datetime.datetime(2024, 10, 7, 4, 0, tzinfo=datetime.timezone.utc),
                          datetime.datetime(2024, 10, 8, 4, 0, tzinfo=datetime.timezone.utc),
                          datetime.datetime(2024, 10, 9, 4, 0, tzinfo=datetime.timezone.utc)],
                         dtype=object),
              'y': array([ 1000000.        ,  1000000.        ,  1000000.        , ...,
                          38140456.50471911, 38736290.87581626, 38733439.95095446])}],
    'layout': {'height': 350,
               'legend': {'orientation': 'h',
                          'traceorder': 'normal',
                          'x': 1,
                          'xanchor': 'right',
                          'y': 1.02,
                          'yanchor': 'bottom'},
               'margin': {'b': 30, 'l': 30, 'r': 30, 't': 30},
               'template': '...',
               'width': 700}
})

Run Portfolio Analysis & Plotting - allocations_from_only_nasdaq100_index

In [110]:
pf_allocations_from_only_nasdaq100_index = vbt.Portfolio.from_orders(
    close=data.get("Close"),
    size=allocations_from_only_nasdaq100_index,
    size_type="targetpercent",
    init_cash=1_000_000,  # Set initial capital to 1M USD
    slippage=0.0005,  # 0.05% slippage (as a decimal fraction)
    fees=0.0005,  # 0.05% commission (as a decimal fraction)
    group_by=True,
    cash_sharing=True,
    call_seq="auto"
)

# Display portfolio statistics
pf_allocations_from_only_nasdaq100_index.stats()

Start Index                    2009-01-02 05:00:00+00:00
End Index                      2024-10-09 04:00:00+00:00
Total Duration                        3969 days 00:00:00
Start Value                                    1000000.0
Min Value                                  861811.028854
Max Value                                 7894897.246517
End Value                                  5331858.92189
Total Return [%]                              433.185892
Benchmark Return [%]                         2099.588672
Position Coverage [%]                          93.751575
Max Gross Exposure [%]                             100.0
Max Drawdown [%]                               51.311096
Max Drawdown Duration                  725 days 00:00:00
Total Orders                                        1076
Total Fees Paid                             163971.44226
Total Trades                                         578
Win Rate [%]                                   60.954064
Best Trade [%]                                180.410989
Worst Trade [%]                               -48.921459
Avg Winning Trade [%]                          22.550134
Avg Losing Trade [%]                          -11.905744
Avg Winning Trade Duration    78 days 16:33:23.478260870
Avg Losing Trade Duration     63 days 13:14:55.927601810
Profit Factor                                   1.463947
Expectancy                                   7844.908821
Sharpe Ratio                                    0.698907
Calmar Ratio                                    0.324287
Omega Ratio                                     1.110603
Sortino Ratio                                   0.977979
Name: group, dtype: object

In [ ]:
pf_allocations_from_only_nasdaq100_index.value.vbt.lineplot()

FigureWidget({
    'data': [{'mode': 'lines',
              'name': 'group',
              'showlegend': True,
              'type': 'scatter',
              'uid': '9107e0ec-8e5e-4f3b-8b16-a05e2c3cd3ce',
              'x': array([datetime.datetime(2009, 1, 2, 5, 0, tzinfo=datetime.timezone.utc),
                          datetime.datetime(2009, 1, 5, 5, 0, tzinfo=datetime.timezone.utc),
                          datetime.datetime(2009, 1, 6, 5, 0, tzinfo=datetime.timezone.utc), ...,
                          datetime.datetime(2024, 10, 7, 4, 0, tzinfo=datetime.timezone.utc),
                          datetime.datetime(2024, 10, 8, 4, 0, tzinfo=datetime.timezone.utc),
                          datetime.datetime(2024, 10, 9, 4, 0, tzinfo=datetime.timezone.utc)],
                         dtype=object),
              'y': array([1000000.        , 1000000.        , 1000000.        , ...,
                          5132857.90300467, 5238746.74595006, 5331858.92188978])}],
    'layout': {'height': 350,
               'legend': {'orientation': 'h',
                          'traceorder': 'normal',
                          'x': 1,
                          'xanchor': 'right',
                          'y': 1.02,
                          'yanchor': 'bottom'},
               'margin': {'b': 30, 'l': 30, 'r': 30, 't': 30},
               'template': '...',
               'width': 700}
})